src/service.c: Use 'input-keyboard' (symbolic) icon as indicator icon on Lomiri.
AyatanaIndicators/ayatana-indicator-keyboard pull request #37
Opened 2022-07-05 20:04 UTC by sunweaver

2022-07-05 20:10 UTC, tari01 reviewed
If we do this, the indicator will stop indicating the current layout!

2022-07-05 20:27 UTC, sunweaver commented
@tari01 That's the intention. At least on Lomiri, the current language icon looks rather clumsy. I will test this patch in MATE tomorrow and I assume that the keyboard icon will be more beautiful there, as well. The current keyboard should be highlighted when opening the indicator's menu.

2022-07-05 21:25 UTC, sunweaver commented
Maybe make this configurable through gsettings for MATE et al?

2022-07-05 21:30 UTC, sunweaver commented
@tari01 See updated PR branch.

2022-07-05 22:26 UTC, tari01 requested changes
GIcon *pIcon = NULL;
    
    if (ayatana_common_utils_is_lomiri())
    {
        m_fnKeyboardGetLayout(self->pPrivate->pKeyboard, -1, &sLanguage, NULL);
        pIcon = g_themed_icon_new_with_default_fallbacks(ICON_DEFAULT);
    }
    else
    {
        gchar *sLanguage;
        m_fnKeyboardGetLayout(self->pPrivate->pKeyboard, -1, &sLanguage, NULL);

        gchar *sIcon = g_strconcat("ayatana-indicator-keyboard-", sLanguage, NULL);
        g_free(sLanguage);

        pIcon = g_themed_icon_new_with_default_fallbacks(sIcon);
        g_free(sIcon);
    }

2022-07-06 06:49 UTC, sunweaver commented
@tari01 Your proposed change doesn't seem to work, e.g. gchar *sLanguage is declared in the else clause whereas it gets used in the upper if clause part. Why do we need sLanguage stuff in both if-and-else-clauses?

2022-07-06 07:14 UTC, tari01 commented
> @tari01 Your proposed change doesn't seem to work, e.g. gchar *sLanguage is declared in the else clause whereas it gets used in the upper if clause part. Why do we need sLanguage stuff in both if-and-else-clauses?

Aaagh, sorry. Copy-paste error. Just drop the `m_fnKeyboardGetLayout` line from upper part.

2022-07-06 11:37 UTC, tari01 requested changes

2022-07-06 11:37 UTC, tari01 commented on src/service.c
> +    GIcon *pIcon = null;
@sunweaver 

Final change: `GIcon *pIcon = NULL;`

2022-07-06 12:10 UTC, tari01 approved these changes

2022-07-06 12:10 UTC, merged